# Generated by Django 5.2.13 on 2026-05-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-id'], 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AlterModelOptions(
            name='joblog',
            options={'ordering': ['id'], 'verbose_name': '任务日志', 'verbose_name_plural': '任务日志'},
        ),
    ]
